<?php

/**
 * @file
 * Localgov Review Date module hooks.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeForm;

/**
 * Implements hook_entity_base_field_info().
 */
function localgov_review_date_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields = [];
    $fields['localgov_review_date'] = BaseFieldDefinition::create('review_date')
      ->setLabel(t('Review date'))
      ->setDisplayOptions('form', [
        'type' => 'review_date',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setComputed(TRUE);
    return $fields;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function localgov_review_date_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\node\NodeForm $node_form */
  $node_form = $form_state->getBuildInfo()['callback_object'];

  if ($node_form instanceof NodeForm) {
    /** @var \Drupal\node\NodeInterface */
    $node = $node_form->getEntity();

    /** @var \Drupal\scheduled_transitions\ScheduledTransitionsUtilityInterface $utility */
    $utility = \Drupal::service('scheduled_transitions.utility');

    $scheduled_bundles = $utility->getBundles();

    if (!isset($scheduled_bundles['node']) || !in_array($node->bundle(), $scheduled_bundles['node'])) {
      $form['localgov_review_date']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function localgov_review_date_form_node_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  localgov_review_date_form_node_form_alter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Add submit handler to the scheduled transitions settings form.
 */
function localgov_review_date_form_scheduled_transitions_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'localgov_review_date_form_scheduled_transitions_settings_submit';
}

/**
 * Clear caches after submitting the scheduled transitions settings form.
 */
function localgov_review_date_form_scheduled_transitions_settings_submit(array $form, FormStateInterface $form_state) {

  // The review date field is only added to nodes that have scheduled
  // transitions enabled. It's necessary to rebuild caches after making changes
  // to scheduled transitions to ensure the field is added.
  drupal_flush_all_caches();
}
